export const theme = {
  color: {
    background: '#E2262C',
    onBackground: '#FFFFFF',
    surface: '#FFFFFF',
    surfaceMuted: '#ECE6D8',
    surfaceSection: 'rgb(244 241 234)',
    border: '#242423',
    textPrimary: '#242423',
    textMuted: '#6B6558',
    textFaint: '#A39C8A',
    primary: '#E2262C',
    primaryStrong: '#B31F24',
    primarySoft: '#FBE0E1',
    accent: '#3B6FE0',
    accentSoft: '#DCE6FB',
    danger: '#DC2626',
    dangerSoft: '#FEE2E2',
    success: '#16A34A',
    successSoft: '#DCFCE7',
  },
  font: {
    display: '"Roboto", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    body: '"Roboto", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    mono: '"SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace',
  },
  radius: {
    sm: '6px',
    md: '10px',
    lg: '16px',
    full: '999px',
  },
  breakpoint: {
    md: '768px',
  },
  shadow: {
    card: '0 2px 0 rgba(36, 36, 35, 0.9)',
    cardHover: '0 4px 0 rgba(36, 36, 35, 0.9)',
    modal: '0 20px 60px rgba(0, 0, 0, 0.18)',
  },
  space: (multiplier) => `${multiplier * 4}px`,
}
